import type { Metadata } from 'next'
import { getFontsAsVariables } from '@/utils/fonts'
import '@/styles/globals.css'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
}

const fontsVariables = getFontsAsVariables()

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="pt-BR">
      <body className={fontsVariables}>{children}</body>
    </html>
  )
}
