import { Fira_Sans, Fira_Mono, Merriweather } from 'next/font/google'
import type { Metadata } from 'next'
import './globals.css'

const sans = Fira_Sans({
  subsets: ['latin'],
  variable: '--font-fira-sans',
  weight: ['200', '400', '600', '800']
})
const serif = Merriweather({
  subsets: ['latin'],
  variable: '--font-merriweather',
  weight: ['400', '700', '900']
})
const mono = Fira_Mono({
  subsets: ['latin'],
  variable: '--font-fira-mono',
  weight: ['400', '500', '700']
})
const fontsVariables = [sans, serif, mono]
  .map(({ variable }) => variable)
  .join(' ')

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="pt-BR">
      <body className={fontsVariables}>{children}</body>
    </html>
  )
}
